version: '3.7'

services:
  
  product-service:
    build: ./product
    volumes:
      - ./product:/code
    ports:
     - "127.0.0.1:5001:80" 

  freshstore-service:
    build: ./freshstore
    volumes: 
      - ./freshstore:/app
    ports: 
      - "127.0.0.1:8080:3000"
    depends_on: 
      - product-service
      